"""discussion migration

Revision ID: b835ddb85775
Revises: b9ee60ac2881
Create Date: 2024-06-14 15:08:09.468742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b835ddb85775'
down_revision = 'b9ee60ac2881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtags', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('hashtags')

    # ### end Alembic commands ###
